apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-multi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-multi
    app.kubernetes.io/part-of: rhtap-devfile-multi-component
  name: devfile-sample-python-basic-multi
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-python-basic-multi
status:
  loadBalancer: {}
