apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-multi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-multi
    app.kubernetes.io/part-of: rhtap-devfile-multi-component
  name: devfile-sample-java-springboot-basic-multi
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-multi
status:
  loadBalancer: {}
